// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Problem struct {
	ID                 int64
	Title              string
	Description        string
	OwnerID            int64
	OwnerName          string
	AcceptedSolutionID sql.NullInt64
	CreatedAt          time.Time
}

type Solution struct {
	ID          int64
	ProblemID   int64
	Title       string
	Description string
	OwnerID     int64
	OwnerName   string
	CreatedAt   time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	FullName  string
	CreatedAt time.Time
}
