// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Problem struct {
	ID          int64
	Title       string
	Description string
}

type Solution struct {
	ID        int64
	Problemid int64
	Solution  string
}

type User struct {
	ID       int64
	Username string
	Password string
}
