// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: problems.sql

package db

import (
	"context"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (
    title, description
) VALUES (
    $1, $2
)
RETURNING id, title, description
`

type CreateProblemParams struct {
	Title       string
	Description string
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, createProblem, arg.Title, arg.Description)
	var i Problem
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const getProblemById = `-- name: GetProblemById :one
SELECT id, title, description FROM problems
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProblemById(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblemById, id)
	var i Problem
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}
