// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package db

import (
	"context"
	"database/sql"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (
    title, description, owner_id, owner_name
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, title, description, owner_id, owner_name, accepted_solution_id
`

type CreateProblemParams struct {
	Title       string
	Description string
	OwnerID     int64
	OwnerName   string
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.Title,
		arg.Description,
		arg.OwnerID,
		arg.OwnerName,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
		&i.AcceptedSolutionID,
	)
	return i, err
}

const deleteProblemByID = `-- name: DeleteProblemByID :exec
DELETE FROM problems WHERE id = $1
`

func (q *Queries) DeleteProblemByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProblemByID, id)
	return err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, description, owner_id, owner_name, accepted_solution_id FROM problems
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProblemByID(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
		&i.AcceptedSolutionID,
	)
	return i, err
}

const getProblems = `-- name: GetProblems :many
SELECT id, title, description, owner_id, owner_name, accepted_solution_id FROM problems
`

func (q *Queries) GetProblems(ctx context.Context) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.OwnerName,
			&i.AcceptedSolutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAcceptedSolutionID = `-- name: SetAcceptedSolutionID :exec
UPDATE problems SET accepted_solution_id = $2
WHERE id = $1
`

type SetAcceptedSolutionIDParams struct {
	ID                 int64
	AcceptedSolutionID sql.NullInt64
}

func (q *Queries) SetAcceptedSolutionID(ctx context.Context, arg SetAcceptedSolutionIDParams) error {
	_, err := q.db.ExecContext(ctx, setAcceptedSolutionID, arg.ID, arg.AcceptedSolutionID)
	return err
}

const unsetAcceptedSolutionID = `-- name: UnsetAcceptedSolutionID :exec
UPDATE problems SET accepted_solution_id = NULL
WHERE id = $1
`

func (q *Queries) UnsetAcceptedSolutionID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unsetAcceptedSolutionID, id)
	return err
}
