// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: solutions.sql

package db

import (
	"context"
)

const createSolution = `-- name: CreateSolution :one
INSERT INTO solutions (
    problem_id, title, description, owner_id, owner_name
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, problem_id, title, description, owner_id, owner_name
`

type CreateSolutionParams struct {
	ProblemID   int64
	Title       string
	Description string
	OwnerID     int64
	OwnerName   string
}

func (q *Queries) CreateSolution(ctx context.Context, arg CreateSolutionParams) (Solution, error) {
	row := q.db.QueryRowContext(ctx, createSolution,
		arg.ProblemID,
		arg.Title,
		arg.Description,
		arg.OwnerID,
		arg.OwnerName,
	)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
	)
	return i, err
}

const getSolutionByID = `-- name: GetSolutionByID :one
SELECT id, problem_id, title, description, owner_id, owner_name FROM solutions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSolutionByID(ctx context.Context, id int64) (Solution, error) {
	row := q.db.QueryRowContext(ctx, getSolutionByID, id)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
	)
	return i, err
}

const getSolutions = `-- name: GetSolutions :many
SELECT id, problem_id, title, description, owner_id, owner_name FROM solutions
`

func (q *Queries) GetSolutions(ctx context.Context) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getSolutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSolutionsByProblemID = `-- name: GetSolutionsByProblemID :many
SELECT id, problem_id, title, description, owner_id, owner_name FROM solutions
WHERE problem_id = $1
`

func (q *Queries) GetSolutionsByProblemID(ctx context.Context, problemID int64) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getSolutionsByProblemID, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
