// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: solutions.sql

package db

import (
	"context"
)

const createSolution = `-- name: CreateSolution :one
INSERT INTO solutions (
    problemId, solution
) VALUES (
    $1, $2
)
RETURNING id, problemid, solution
`

type CreateSolutionParams struct {
	Problemid int64
	Solution  string
}

func (q *Queries) CreateSolution(ctx context.Context, arg CreateSolutionParams) (Solution, error) {
	row := q.db.QueryRowContext(ctx, createSolution, arg.Problemid, arg.Solution)
	var i Solution
	err := row.Scan(&i.ID, &i.Problemid, &i.Solution)
	return i, err
}
