// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, password, full_name
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreateUserParams struct {
	Username string
	Password string
	FullName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.FullName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getCredentialsByUsername = `-- name: GetCredentialsByUsername :one
SELECT id, username, password FROM users
WHERE username = $1 LIMIT 1
`

type GetCredentialsByUsernameRow struct {
	ID       int64
	Username string
	Password string
}

func (q *Queries) GetCredentialsByUsername(ctx context.Context, username string) (GetCredentialsByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getCredentialsByUsername, username)
	var i GetCredentialsByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, full_name FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID       int64
	Username string
	FullName string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Username, &i.FullName)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, full_name FROM users
WHERE username = $1 LIMIT 1
`

type GetUserByUsernameRow struct {
	ID       int64
	Username string
	FullName string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.FullName)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, full_name FROM users
`

type GetUsersRow struct {
	ID       int64
	Username string
	FullName string
}

func (q *Queries) GetUsers(ctx context.Context) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
